import React from 'react';
import { FaFire, FaGem, FaInfinity, FaHeart, FaFeatherAlt } from 'react-icons/fa';
import { IoSparklesOutline, IoPulseOutline } from 'react-icons/io5';

const navLinks = [
  { name: "Inicio", link: "/" },
  { name: "Tienda", link: "/tienda" },
  { name: "Información", link: "/informacion" },
];

const words = [ { text: "placer 🔥" }, { text: "pasión 💋" }, { text: "resistencia 💪" }, { text: "deseo 🍑" }, { text: "intensidad 💦" }, { text: "conexión ❤️" },];
const counterItems = [ { value: 4, suffix: "+", label: "Años de Experiencia" }, { value: 200000, suffix: "+", label: "Clientes Satisfechos" }, { value: 10000, suffix: "+", label: "Testimonios Positivos" }, { value: 100, suffix: "%", label: "Ingredientes Naturales" },];
const logoIconsList = [ { imgPath: "/images/logos/company-logo-1.png", }, { imgPath: "/images/logos/company-logo-2.png", }, { imgPath: "/images/logos/company-logo-3.png", }, { imgPath: "/images/logos/company-logo-4.png", }, { imgPath: "/images/logos/company-logo-5.png", }, { imgPath: "/images/logos/company-logo-6.png", }, { imgPath: "/images/logos/company-logo-7.png", }, { imgPath: "/images/logos/company-logo-8.png", }, { imgPath: "/images/logos/company-logo-9.png", }, { imgPath: "/images/logos/company-logo-10.png", }, { imgPath: "/images/logos/company-logo-11.png", }, ];
const abilities = [ { imgPath: "/images/seo.png", title: "Quality Focus", desc: "Delivering high-quality results...", }, { imgPath: "/images/chat.png", title: "Reliable Communication", desc: "Keeping you updated...", }, { imgPath: "/images/time.png", title: "On-Time Delivery", desc: "Making sure projects are completed...", }, ];
const techStackImgs = [ { name: "React Developer", imgPath: "/images/logos/react.png", }, { name: "Python Developer", imgPath: "/images/logos/python.svg", }, { name: "Backend Developer", imgPath: "/images/logos/node.png", }, { name: "Interactive Developer", imgPath: "/images/logos/three.png", }, { name: "Project Manager", imgPath: "/images/logos/git.svg", }, ];

const commonIngredients = ["Sulfato Ferroso", "Sorbitol 70%", "Propilenglicol", "Ginseng", "Vitamina C", "Vitamina B1", "Vitamina B2", "Vitamina B3", "Vitamina B6", "Ácido Fólico", "Sabor Caramelo", "Agua Purificada"];
const commonBenefits = ["Aumenta los niveles de energía y vitalidad.", "Ayuda a combatir el cansancio y la fatiga.", "Apoya el rendimiento físico y sexual.", "Fortalece el sistema inmunológico."];
const commonWarnings = ["Este es un suplemento dietario, no es un medicamento.", "No consumir en estado de embarazo o lactancia sin consultar a su médico.", "No apto para menores de 18 años.", "Si padece alguna condición médica, consulte a su médico antes de consumir."];

const vitaferProducts = [
  { id: "vitafer-l-500ml-x1", name: "💥 Vitafer-L 500mL (1 Botella)", modelPath: "/images/vitafer-bottle.png", price: "$ 1000", presentation: "1 Frasco de 500 mL", description: "El clásico multivitamínico que enciende tu energía. Ideal para el rendimiento diario y la resistencia.", category: "Productos Individuales", ingredients: commonIngredients, benefits: commonBenefits, warnings: commonWarnings, detailedDescription: "Vitafer-L en su presentación de 500mL es la fórmula tradicional y robusta para quienes buscan un impulso significativo en su día a día." },
  { id: "vitafer-l-500ml-x2", name: "🎁 Pack x2 Vitafer-L 500mL", modelPath: "/images/2-botellas.png", price: "$ 1700", presentation: "Pack de 2 Frascos de 500 mL", description: "¡Duplica la potencia y ahorra! Lleva dos frascos para un suministro prolongado de energía y vitalidad.", category: "Promociones", ingredients: commonIngredients, benefits: commonBenefits, warnings: commonWarnings, detailedDescription: "Aprovecha nuestro pack de dos frascos de Vitafer-L 500mL. Ideal para parejas o para quienes desean asegurar su vitalidad por más tiempo." },
  { id: "vitafer-l-sachet-x1", name: "🔥 Vitafer-L Sachet (1 Caja)", modelPath: "/images/sachet.png", price: "$ 900", presentation: "1 Caja (Display x 15 sobres)", description: "Potencia en formato práctico. Llévalo contigo y recárgate cuando quieras. Ideal para encuentros espontáneos.", category: "Productos Individuales", ingredients: commonIngredients, benefits: commonBenefits, warnings: commonWarnings, detailedDescription: "La presentación en sachet de Vitafer-L ofrece la misma fórmula potente en un formato individual, práctico y discreto." },
  { id: "vitafer-l-sachet-x2", name: "🎁 Pack x2 Cajas de Sachet", modelPath: "/images/2-cajas-sachet.png", price: "$ 1500", presentation: "Pack de 2 Cajas (30 sobres total)", description: "¡Doble dosis de practicidad y ahorro! Lleva dos cajas de sachets y mantén la energía siempre a mano.", category: "Promociones", ingredients: commonIngredients, benefits: commonBenefits, warnings: commonWarnings, detailedDescription: "Asegura tu suministro de energía para llevar con este pack de dos cajas de Vitafer-L Sachet. Perfecto para un uso regular o para compartir." },
  { id: "mayoreo-vitafer-sachet-12cajas", name: "📦 Mayoreo: 12 Cajas de Sachet", modelPath: "/images/12-satches.png", price: "$ 7200", presentation: "Paquete Mayorista: 12 Cajas (180 sachets)", description: "¡Ideal para negocios o reventa! Adquiere 12 cajas de nuestros prácticos Vitafer-L Sachets.", category: "Mayoreo", ingredients: commonIngredients, benefits: commonBenefits, warnings: commonWarnings, detailedDescription: "Maximiza tu inventario con este paquete mayorista de Vitafer-L en Sachets. Recibirás 12 displays, cada uno con 15 sachets (un total de 180 unidades)." },
  { id: "mayoreo-vitafer-l-500ml-25", name: "📦 Mayoreo: 25 x Vitafer-L 500mL", modelPath: "/images/vitafer-box.png", price: "$ 12000", presentation: "Paquete Mayorista: 1 Caja con 25 Frascos", description: "¡Máximo ahorro para distribuidores! Llévate 25 botellas a un precio increíble y maximiza tus ganancias.", category: "Mayoreo", ingredients: commonIngredients, benefits: commonBenefits, warnings: commonWarnings, detailedDescription: "Este paquete mayorista de Vitafer-L 500mL es la mejor opción para distribuidores establecidos que buscan el mejor precio por unidad." },
];

const vitaferOffers = [];

const archivedProducts = [
    { id: "vitafer-l-500ml-x3", name: "💥 Pack x3 Vitafer-L 500mL", modelPath: "/images/3-botellas.png", price: "$ 2200", presentation: "Pack de 3 Frascos de 500 mL c/u", description: "¡El mejor valor! Equípate con nuestro pack de tres frascos...", category: "Archivado", sku: "VTFL500ML-X3" },
    { id: "vitafer-l-shots-20ml", name: "🔞 Vitafer-L Shots 20mL", modelPath: "/images/bottles-pack.png", price: "$ 2000", originalPrice: "$ 2500", presentation: "Display x 24 shots de 20mL c/u", description: "La dosis explosiva para noches inolvidables...", category: "Archivado", sku: "VTFLSHOT20ML-D24" },
    { id: "mayoreo-vitafer-shots-12cajas", name: "📦 Mayoreo: 12 Cajas x 24 Shots 20mL", modelPath: "/images/vitafer-pack.png", price: "$12515", unitDescription: "por paquete de 12 cajas", presentation: "Paquete Mayorista: 12 Displays...", category: "Archivado", sku: "VTFLSHOT20ML-MAYOR12D" },
];

const expCards = [ { title: "Energía Que Excita", description: "Siente cómo una chispa recorre tu cuerpo...", icon: <FaFire />, bgColor: "from-black via-red-950/30 to-zinc-900", accentColor: "text-red-400", }, { title: "Poder Irresistible", description: "Irradia una confianza que atrae miradas...", icon: <FaGem />, bgColor: "from-zinc-900 via-purple-950/40 to-black", accentColor: "text-purple-400", }, { title: "Explosión de Vitalidad", description: "Olvida la fatiga. Libera una energía...", icon: <IoSparklesOutline />, bgColor: "from-black via-orange-950/30 to-zinc-900", accentColor: "text-orange-400", }, ];
const expCards2 = [ { title: "Fuerza Que Dura", description: "Supera tus límites y prolonga el placer...", icon: <FaInfinity />, bgColor: "from-zinc-900 via-amber-950/30 to-black", accentColor: "text-amber-400", }, { title: "Intimidad Explosiva", description: "Profundiza el vínculo más allá de la piel...", icon: <FaHeart />, bgColor: "from-black via-teal-950/30 to-zinc-900", accentColor: "text-teal-400", }, { title: "Relajación Sensual", description: "Disuelve el estrés y sumérgete...", icon: <FaFeatherAlt />, bgColor: "from-zinc-900 via-indigo-950/30 to-black", accentColor: "text-indigo-400", }, ];
const expLogos = [ { name: "logo1", imgPath: "/images/logo1.png", }, { name: "logo2", imgPath: "/images/logo2.png", }, { name: "logo3", imgPath: "/images/logo3.png", }, ];
const testimonials = [ { name: "Carlos Gómez", mentions: "@carlosgomez", review: "Desde que empecé a tomar Vitafer...", imgPath: "/images/perfiles/perfil1.jpg", }, { name: "Lucía Martínez", mentions: "@luciamtz", review: "Lo compré para mi pareja y el cambio fue impresionante...", imgPath: "/images/perfiles/perfil5.jpg", }, { name: "Jorge Ramírez", mentions: "@jramirez", review: "Vitafer me ayudó a quitarme el cansancio que tenía...", imgPath: "/images/perfiles/perfil3.jpg", }, { name: "Valentina Ríos", mentions: "@valentinar", review: "Quedé sorprendida con los resultados...", imgPath: "/images/perfiles/perfil4.jpg", }, { name: "Pedro Torres", mentions: "@pedritot", review: "Probé varios productos, pero ninguno me dio...", imgPath: "/images/perfiles/perfil2.jpg", }, { name: "Camila Fernández", mentions: "@camilafdz", review: "Mi pareja notó el cambio de inmediato...", imgPath: "/images/perfiles/perfil6.jpg", }, ];
const socialImgs = [ { name: "insta", imgPath: "/images/insta.png", }, { name: "fb", imgPath: "/images/fb.png", }, { name: "x", imgPath: "/images/x.png", }, { name: "linkedin", imgPath: "/images/linkedin.png", }, ];

export {
  words, abilities, logoIconsList, counterItems, expCards, expCards2, 
  expLogos, testimonials, socialImgs, vitaferProducts, vitaferOffers,
  techStackImgs, navLinks,
  archivedProducts
};